// WRAM.v

// Generated using ACDS version 20.2 50

`timescale 1 ps / 1 ps
module WRAM (
		input  wire [287:0] data,    //    data.datain
		output wire [287:0] q,       //       q.dataout
		input  wire [3:0]   address, // address.address
		input  wire         wren,    //    wren.wren
		input  wire         clock    //   clock.clk
	);

	WRAM_ram_1port_2010_wx3dkoi ram_1port_0 (
		.data    (data),    //   input,  width = 288,    data.datain
		.q       (q),       //  output,  width = 288,       q.dataout
		.address (address), //   input,    width = 4, address.address
		.wren    (wren),    //   input,    width = 1,    wren.wren
		.clock   (clock)    //   input,    width = 1,   clock.clk
	);

endmodule
